### ISSUE TITLE
Courses to be completed

### ISSUE THREAD

**Issue by adamgamble548** [adamgamble548/My-Portfolio#1]
## To-do

- [x] Git Basics on https://teamtreehouse.com/library/git-basics
- [ ] Github Basics on https://teamtreehouse.com/library/github-basics
- [ ] Sass course on https://teamtreehouse.com/library/sass-basics-2
- [ ] Advanced Sass on https://teamtreehouse.com/library/advanced-sass
